package demo.hibrid.stats;

public enum EventType {
    MESSAGE_RECEIVED,
    MESSAGE_SCHEDULED,
    EARLY_SCHEDULER_STARTED,
    EARLY_SCHEDULER_ENDED,
    LATE_SCHEDULER_WILL_TAKE_COMMAND,
    LATE_SCHEDULER_STARTED,
    LATE_SCHEDULER_ENDED,
    REPLICA_WORKER_WILL_TAKE_COMMAND,
    REPLICA_WORKER_STARTED,
    REPLICA_WORKER_ENDED,
    COMMAND_REMOVED,
    COMMAND_REPLIED,
    REPLY_SENT,
}
